# Generated by Django 2.2.19 on 2021-02-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberbullying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='issue_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_reported',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='issue_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
