# Generated by Django 2.2.19 on 2021-02-27 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cyberbullying', '0002_auto_20210227_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='issue_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
